In [3]:
#!pip install kaggle

In [4]:
#!kaggle datasets list -s "goal leagues"

In [5]:
#!kaggle datasets download shreyanshkhandelwal/goal-dataset-top-5-european-leagues

## A. Import Data Set Goal Scorer

In [7]:
import pandas as pd

In [10]:
df = pd.read_csv("epl-goalScorer(20-21).csv")
df

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,517,9415,Jaden Philogene-Bidace,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Aston Villa,0,0.000000,0.056044,0.056044
518,518,9423,Gaetano Berardi,2,113,0,0.074761,0,0.000000,1,0,0,0,D S,Leeds,0,0.074761,0.231278,0.231278
519,519,9524,Anthony Elanga,1,67,0,0.000000,0,0.000000,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
520,520,9540,Femi Seriki,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Sheffield United,0,0.000000,0.000000,0.000000
521,521,9552,Tyrese Francois,1,13,0,0.000000,0,0.000000,0,0,0,0,S,Fulham,0,0.000000,0.000000,0.000000

In [11]:
# formating dataframe supaya semua dataset dapat muncul 

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 3)

In [13]:
df

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.175,14,7.577,138,49,1,0,F,Tottenham,19,19.130,24.996,4.451
1,1,1250,Mohamed Salah,37,3085,22,20.251,5,6.529,126,55,0,0,F M S,Liverpool,16,15.684,28.968,9.800
2,2,1228,Bruno Fernandes,37,3117,18,16.019,12,11.475,121,95,6,0,M S,Manchester United,9,8.408,26.911,11.932
3,3,453,Son Heung-Min,37,3139,17,11.023,10,9.513,68,75,0,0,F M S,Tottenham,16,10.262,20.672,6.609
4,4,822,Patrick Bamford,38,3085,17,18.402,7,3.782,107,30,3,0,F S,Leeds,15,16.880,23.395,4.132
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136,0,2.102,82,18,3,0,F S,Everton,16,18.136,19.699,4.159
6,6,755,Jamie Vardy,34,2848,15,19.943,9,5.088,82,28,1,0,F S,Leicester,7,13.092,18.228,2.413
7,7,8865,Ollie Watkins,37,3330,14,16.280,5,5.314,98,45,2,1,F,Aston Villa,13,14.758,22.014,5.335
8,8,314,Ilkay GÃ¼ndogan,28,2033,13,9.567,2,3.816,54,42,1,0,M S,Manchester City,12,8.045,19.287,10.148
9,9,3277,Alexandre Lacazette,30,1928,13,12.029,2,2.209,45,22,3,0,F M S,Arsenal,10,9.745,14.362,2.938
10,10,468,Callum Wilson,26,2079,12,13.590,5,3.046,49,17,2,0,F S,Newcastle United,8,10.545,14.206,1.053
11,11,620,Kelechi Iheanacho,25,1452,12,9.049,2,3.534,59,28,1,0,F S,Leicester,12,8.287,13.962,3.430
12,12,986,Danny Ings,28,2115,12,8.139,4,2.311,56,22,1,0,F S,Southampton,10,6.617,9.929,2.063
13,13,4456,Chris Wood,32,2675,12,12.896,3,2.038,69,23,0,0,F S,Burnley,10,11.374,13.585,2.150
14,14,522,Wilfried Zaha,30,2615,11,8.804,2,3.703,60,30,6,0,F M S,Crystal Palace,9,7.282,13.579,3.634
15,15,556,Marcus Rashford,37,2941,11,9.580,9,4.185,79,44,4,0,F M S,Manchester United,11,9.580,20.442,8.927
16,16,838,Sadio ManÃ©,35,2805,11,14.829,7,7.788,94,61,3,0,F M S,Liverpool,11,14.829,24.999,6.058
17,17,2251,Gareth Bale,20,909,11,5.798,2,1.842,38,21,1,0,M S,Tottenham,11,5.798,8.150,2.595
18,18,7153,Matheus Pereira,33,2594,11,6.948,6,6.356,65,58,2,1,M S,West Bromwich Albion,7,3.904,10.857,3.758
19,19,318,Pierre-Emerick Aubameyang,28,2254,10,10.194,3,2.352,55,19,2,0,F M S,Arsenal,8,8.672,14.779,3.955
20,20,531,Michail Antonio,25,1923,10,14.139,5,3.035,63,25,3,0,F S,West Ham,10,14.139,18.999,2.655
21,21,606,Christian Benteke,30,1824,10,7.457,1,0.698,71,15,1,1,F S,Crystal Palace,10,7.457,8.473,3.154
22,22,618,Raheem Sterling,30,2449,10,11.763,6,5.817,68,35,3,0,F M S,Manchester City,10,11.002,24.089,11.477
23,23,3294,Edinson Cavani,26,1355,10,8.603,3,2.317,34,14,4,0,F S,Manchester United,10,8.603,12.259,2.731
24,24,5612,Anwar El Ghazi,28,1612,10,9.038,0,1.883,64,26,2,0,F M S,Aston Villa,6,5.993,7.846,2.691
25,25,8288,Tomas Soucek,37,3330,10,8.936,1,2.330,63,17,7,1,M,West Ham,10,8.936,16.730,8.610
26,26,482,Roberto Firmino,36,2882,9,12.860,7,6.117,83,44,2,0,F M S,Liverpool,9,12.860,25.271,10.199
27,27,558,Jesse Lingard,15,1344,9,5.095,4,2.329,39,18,3,0,F M,West Ham,8,3.573,9.869,5.617
28,28,750,Riyad Mahrez,26,1894,9,6.151,5,5.955,56,43,0,0,F M S,Manchester City,9,6.151,18.641,9.020
29,29,6681,Harvey Barnes,25,1954,9,6.697,4,1.772,56,26,0,0,F M S,Leicester,9,6.697,8.894,1.595
30,30,6854,Diogo Jota,19,1114,9,7.058,0,1.763,46,12,2,0,F M S,Liverpool,9,7.058,10.973,4.076
31,31,7700,Che Adams,36,2685,9,12.119,5,5.228,55,37,1,0,F S,Southampton,9,12.119,14.487,2.745
32,32,843,James Ward-Prowse,37,3330,8,5.427,7,3.957,42,57,5,0,D M,Southampton,5,2.382,10.151,8.929
33,33,1776,Jarrod Bowen,37,2514,8,7.817,5,4.952,53,28,0,0,F M S,West Ham,8,7.817,14.000,3.097
34,34,3621,Neal Maupay,33,2526,8,13.774,2,4.277,71,32,1,1,F M S,Brighton,5,10.729,17.158,3.382
35,35,5543,Gabriel Jesus,28,1977,8,9.010,4,3.372,52,29,2,0,F M S,Manchester City,8,9.010,16.565,5.564
36,36,5656,Nicolas Pepe,28,1512,8,5.811,1,1.012,43,11,1,1,F M S,Arsenal,7,5.050,9.171,4.218
37,37,6055,Phil Foden,27,1548,8,5.438,5,4.749,43,36,0,0,F M S,Manchester City,8,5.438,13.111,5.408
38,38,6630,Joe Willock,21,1215,8,5.088,0,0.734,23,10,1,0,M S,"Arsenal,Newcastle United",8,4.327,7.007,2.988
39,39,6818,James Maddison,31,2123,8,3.828,5,5.387,75,50,4,0,M S,Leicester,8,3.828,11.743,6.073
40,40,8718,Stuart Dallas,38,3412,8,4.457,2,2.085,48,26,7,0,D M,Leeds,8,4.457,18.534,13.810
41,41,8720,Jack Harrison,36,2871,8,6.254,8,7.523,46,59,2,0,M S,Leeds,8,6.254,19.397,8.036
42,42,695,Bertrand TraorÃ©,36,2362,7,6.304,6,4.571,64,35,1,0,F M S,Aston Villa,7,6.304,9.835,1.332
43,43,1389,Jorginho,28,2022,7,6.973,1,1.955,14,24,2,0,M S,Chelsea,0,0.122,11.384,10.879
44,44,2381,Rodrigo,26,1285,7,5.756,2,3.201,46,31,3,0,F M S,Leeds,7,5.756,10.816,4.349
45,45,6026,Richarlison,33,2803,7,10.427,3,3.395,78,25,3,1,F M S,Everton,6,9.666,15.679,5.174
46,46,6441,FerrÃ¡n Torres,23,1291,7,5.729,2,2.202,36,18,1,0,F M S,Manchester City,7,5.729,9.769,2.724
47,47,7490,Mason Greenwood,31,1825,7,6.976,2,2.428,67,14,2,0,F M S,Manchester United,7,6.976,14.032,5.954
48,48,7711,David McGoldrick,34,2319,7,7.383,1,1.050,65,16,7,0,F M S,Sheffield United,7,7.383,9.682,3.188
49,49,65,Timo Werner,35,2605,6,13.433,8,6.667,80,36,2,0,F M S,Chelsea,6,13.433,20.533,5.242
50,50,501,Danny Welbeck,24,1551,6,7.380,1,3.231,35,22,0,0,F M S,Brighton,6,6.619,10.266,1.477
51,51,675,Jack Grealish,26,2187,6,5.193,10,9.334,50,81,5,0,F M S,Aston Villa,6,5.193,17.487,6.972
52,52,702,Tammy Abraham,22,1027,6,6.189,1,0.721,32,9,0,0,F S,Chelsea,6,6.189,7.901,2.122
53,53,714,Gylfi Sigurdsson,35,2189,6,5.620,5,4.764,46,43,2,0,F M S,Everton,3,3.337,8.378,3.661
54,54,2249,James RodrÃ­guez,23,1802,6,3.364,4,5.440,37,40,4,0,F M S,Everton,6,3.364,12.033,7.104
55,55,5956,Youri Tielemans,38,3359,6,4.168,4,3.312,48,49,6,0,M S,Leicester,4,2.646,18.975,14.945
56,56,7768,Mason Mount,36,2891,6,6.885,5,9.848,82,87,2,0,F M S,Chelsea,5,6.124,21.696,12.443
57,57,8026,Raphinha,30,2369,6,6.219,9,9.525,67,65,3,0,M S,Leeds,6,6.219,16.793,6.680
58,58,447,Kevin De Bruyne,24,1918,5,9.908,11,10.004,79,72,1,0,M S,Manchester City,3,7.625,21.079,10.636
59,59,935,Kurt Zouma,24,2024,5,3.137,0,0.081,27,4,3,0,D S,Chelsea,5,3.137,6.216,6.133
60,60,4476,Callum Robinson,28,1580,5,3.203,0,1.050,31,16,0,0,F M S,West Bromwich Albion,5,3.203,5.217,1.596
61,61,6048,Lewis Dunk,32,2844,5,2.699,0,0.831,31,10,5,2,D,Brighton,5,2.699,8.266,7.871
62,62,6382,Pedro Neto,31,2570,5,5.495,6,5.738,62,61,4,0,F M S,Wolverhampton Wanderers,5,5.495,11.517,4.207
63,63,6827,Bobby Reid,33,2394,5,4.270,2,1.310,34,14,7,0,D F M S,Fulham,5,4.270,8.203,3.131
64,64,6853,RÃºben Neves,35,2591,5,4.715,1,2.003,65,32,7,0,M S,Wolverhampton Wanderers,2,2.432,6.769,4.476
65,65,7322,Bukayo Saka,31,2561,5,7.169,3,4.512,61,38,1,0,D F M S,Arsenal,5,7.169,18.292,9.180
66,66,7698,Leandro Trossard,34,2601,5,5.413,5,5.398,58,51,2,0,F M S,Brighton,5,5.413,15.999,7.632
67,67,87,Joelinton,31,2006,4,5.631,2,2.366,43,17,3,0,F M S,Newcastle United,3,4.870,9.268,3.285
68,68,502,Olivier Giroud,17,750,4,5.070,0,1.176,29,6,1,0,F S,Chelsea,4,5.070,5.245,1.711
69,69,553,Anthony Martial,22,1494,4,7.406,3,2.620,42,17,0,1,F M S,Manchester United,4,7.406,11.815,3.320
70,70,586,John Stones,21,1843,4,2.394,0,0.047,14,2,0,1,D,Manchester City,4,2.394,9.842,9.743
71,71,2662,Christian Pulisic,27,1739,4,6.775,2,2.761,43,25,2,0,F M S,Chelsea,4,6.775,14.594,7.101
72,72,4105,RaÃºl JimÃ©nez,10,824,4,2.361,0,0.633,26,6,0,0,F,Wolverhampton Wanderers,4,2.361,3.684,1.233
73,73,4381,Mateusz Klich,35,2404,4,3.000,5,3.651,36,44,6,0,M S,Leeds,2,1.478,14.608,10.386
74,74,5220,Kai Havertz,27,1523,4,6.352,3,1.553,33,18,2,0,F M S,Chelsea,4,6.352,10.383,4.812
75,75,5556,Ademola Lookman,34,2765,4,6.251,4,5.258,69,61,5,0,F M S,Fulham,4,5.490,15.355,7.334
76,76,5560,Scott McTominay,32,2121,4,1.848,1,2.115,26,17,3,0,M S,Manchester United,4,1.848,10.912,7.905
77,77,6893,Stuart Armstrong,32,2701,4,2.563,5,2.518,51,33,3,0,M S,Southampton,4,2.563,9.480,6.250
78,78,7420,Miguel AlmirÃ³n,34,2458,4,3.509,1,3.136,33,31,3,0,F M S,Newcastle United,4,3.509,9.295,3.899
79,79,8706,Eberechi Eze,34,2570,4,2.495,6,3.742,37,42,3,0,M S,Crystal Palace,4,2.495,7.996,3.960
80,80,8778,Fabio Silva,31,1251,4,5.959,2,1.035,45,10,2,0,F S,Wolverhampton Wanderers,3,5.197,4.898,1.070
81,81,101,Allan Saint-Maximin,25,1578,3,2.826,4,4.013,30,29,0,0,F M S,Newcastle United,3,2.826,10.595,4.224
82,82,111,Jannik Vestergaard,29,2481,3,2.027,0,0.741,22,7,3,1,D S,Southampton,3,2.027,5.854,5.779
83,83,239,Pascal GroÃŸ,33,2379,3,5.011,8,5.368,32,69,3,0,D M S,Brighton,0,1.966,10.404,6.732
84,84,503,Theo Walcott,22,1660,3,2.281,3,1.263,29,17,0,0,F M S,"Everton,Southampton",3,2.281,5.552,2.234
85,85,528,Angelo Ogbonna,27,2403,3,1.696,0,0.428,13,4,5,0,D,West Ham,3,1.696,3.930,3.707
86,86,592,Ross Barkley,26,1574,3,3.700,1,4.319,39,40,0,0,M S,"Aston Villa,Chelsea",3,3.700,9.897,3.717
87,87,669,Ashley Westwood,37,3322,3,1.006,3,6.352,19,49,7,0,M,Burnley,3,1.006,10.011,6.287
88,88,773,Aleksandar Mitrovic,27,1369,3,5.677,3,2.925,59,23,3,0,F S,Fulham,2,4.155,7.808,1.849
89,89,782,Ben Chilwell,27,2296,3,2.985,5,2.456,27,30,3,0,D M,Chelsea,3,2.985,11.331,8.155
90,90,804,Craig Dawson,21,1835,3,2.692,0,0.054,15,2,3,1,D,West Ham,3,2.692,2.927,2.927
91,91,964,Kyle Bartley,30,2581,3,2.601,1,0.760,14,7,4,0,D S,West Bromwich Albion,3,2.601,2.485,1.499
92,92,1017,Matej Vydra,27,1322,3,5.373,2,2.118,35,14,0,0,F S,Burnley,3,5.373,6.426,1.047
93,93,1653,Michael Keane,34,2896,3,1.505,1,1.085,16,7,4,0,D S,Everton,3,1.505,6.840,6.564
94,94,1740,Paul Pogba,26,1893,3,2.988,3,2.067,31,24,3,0,M S,Manchester United,3,2.988,11.691,7.444
95,95,2335,Pablo Fornals,32,2513,3,5.854,3,2.055,46,28,3,0,F M S,West Ham,3,5.854,14.868,8.321
96,96,3293,Lucas Moura,30,1392,3,1.947,4,2.064,18,16,1,0,F M S,Tottenham,3,1.947,7.514,5.200
97,97,3428,HÃ©lder Costa,22,1152,3,2.598,3,0.628,16,7,0,0,M S,Leeds,3,2.598,4.516,2.207
98,98,3491,Romain Saiss,26,2319,3,3.100,0,0.648,27,4,2,0,D,Wolverhampton Wanderers,3,3.100,4.539,3.721
99,99,3683,Ivan Cavaleiro,36,2477,3,5.549,0,2.680,47,42,2,0,D F M S,Fulham,2,4.026,8.241,2.857
100,100,4422,Ashley Barnes,21,1341,3,3.874,0,0.801,38,19,4,0,F M S,Burnley,2,3.113,4.190,1.199
101,101,5587,Josh Maja,15,809,3,4.918,0,0.743,21,7,0,0,F S,Fulham,2,4.157,4.449,0.646
102,102,5595,Daniel James,14,830,3,1.943,0,0.741,16,7,3,0,M S,Manchester United,3,1.943,4.284,1.736
103,103,5962,Tanguy NDombele Alvaro,33,2141,3,1.530,2,2.126,18,14,3,0,M S,Tottenham,3,1.530,10.935,8.006
104,104,6144,SÃ©bastien Haller,16,933,3,2.555,0,1.135,25,10,0,0,F S,West Ham,3,2.555,3.660,0.853
105,105,7712,Billy Sharp,16,723,3,2.983,0,0.583,9,4,1,0,F S,Sheffield United,1,1.461,2.651,0.665
106,106,7723,John McGinn,37,3330,3,2.167,5,3.502,45,42,12,0,M,Aston Villa,3,2.167,14.868,9.946
107,107,8239,Takumi Minamino,18,941,3,2.557,0,0.763,18,4,1,0,F M S,"Liverpool,Southampton",3,2.557,5.955,2.768
108,108,8291,Daniel Podence,24,1718,3,2.744,2,1.839,32,21,3,0,F M S,Wolverhampton Wanderers,3,2.744,6.725,2.911
109,109,9290,Mbaye Diagne,16,1205,3,6.248,2,0.986,25,10,2,0,F S,West Bromwich Albion,3,6.248,8.730,1.773
110,110,343,Pierre-Emile HÃ¸jbjerg,38,3420,2,1.138,4,1.756,14,16,9,0,M,Tottenham,2,1.138,16.206,14.680
111,111,619,Sergio AgÃ¼ero,11,533,2,3.002,1,1.316,15,7,0,0,F M S,Manchester City,1,1.480,3.364,1.145
112,112,725,Ola Aina,31,2683,2,0.848,1,1.553,14,15,3,0,D M,Fulham,2,0.848,6.773,6.120
113,113,757,Jeffrey Schlupp,27,1424,2,2.015,3,2.573,18,18,3,0,M S,Crystal Palace,2,2.015,5.158,3.467
114,114,766,Jamaal Lascelles,19,1633,2,0.765,0,0.067,16,2,4,0,D,Newcastle United,2,0.765,2.606,2.350
115,115,770,Ayoze PÃ©rez,25,1326,2,4.037,1,1.249,31,23,2,0,F M S,Leicester,2,4.037,9.873,6.760
116,116,771,Georginio Wijnaldum,38,2961,2,2.817,0,1.663,31,21,1,0,M S,Liverpool,2,2.817,13.922,10.476
117,117,790,Nathan Redmond,28,1628,2,3.793,3,2.987,44,22,1,0,F M S,Southampton,2,3.793,8.591,3.183
118,118,807,Jonny Evans,28,2483,2,1.856,2,0.539,8,10,7,0,D,Leicester,2,1.856,8.731,7.943
119,119,900,Adama TraorÃ©,36,2604,2,1.995,2,5.228,41,54,4,0,D F M S,Wolverhampton Wanderers,2,1.995,9.373,3.006
120,120,1024,Tyrone Mings,36,3194,2,2.062,2,0.376,19,7,4,1,D,Aston Villa,2,2.062,6.932,6.709
121,121,1621,Marcos Alonso,13,962,2,1.824,0,1.722,22,15,2,0,D S,Chelsea,2,1.824,4.643,2.536
122,122,1654,Ben Mee,30,2695,2,1.619,0,0.805,22,7,3,0,D,Burnley,2,1.619,2.118,2.016
123,123,1663,Johann Berg Gudmundsson,21,1279,2,1.516,0,0.960,18,10,2,0,M S,Burnley,2,1.516,3.596,1.326
124,124,1678,Michy Batshuayi,18,706,2,1.363,1,1.655,12,9,0,0,F S,Crystal Palace,2,1.363,3.708,1.476
125,125,1687,Harry Maguire,34,3049,2,1.484,1,0.291,36,7,11,0,D,Manchester United,2,1.484,13.127,13.018
126,126,1726,Abdoulaye DoucourÃ©,28,2409,2,2.370,3,2.382,18,20,6,0,M,Everton,2,2.370,10.356,6.734
127,127,1737,Matt Phillips,33,1823,2,2.924,1,3.246,22,25,1,0,M S,West Bromwich Albion,2,2.924,7.041,2.613
128,128,1738,Hal Robson-Kanu,19,522,2,1.496,0,0.243,13,5,2,0,F S,West Bromwich Albion,2,1.496,2.264,0.634
129,129,1746,Jeff Hendrick,22,1436,2,1.108,1,1.433,10,6,1,1,M S,Newcastle United,2,1.108,3.606,1.387
130,130,1791,Trent Alexander-Arnold,36,3040,2,2.593,7,8.576,55,77,2,0,D S,Liverpool,2,2.593,23.108,17.649
131,131,2379,JoÃ£o Cancelo,28,2309,2,1.866,3,5.178,35,45,5,1,D M S,Manchester City,2,1.866,18.106,14.481
132,132,2496,Rodri,33,2719,2,2.539,2,2.335,31,33,6,0,M S,Manchester City,1,1.777,20.215,18.323
133,133,3203,Issa Diop,17,1378,2,0.954,0,0.018,3,1,3,0,D S,West Ham,2,0.954,2.148,1.832
134,134,3288,Thiago Silva,23,1938,2,1.321,0,0.291,13,5,3,1,D,Chelsea,2,1.321,7.843,7.637
135,135,3389,Benjamin Mendy,13,955,2,0.334,1,0.301,6,5,2,0,D M S,Manchester City,2,0.334,2.769,2.349
136,136,3600,Serge Aurier,19,1619,2,1.475,3,3.719,15,17,0,0,D M,Tottenham,2,1.475,8.712,5.293
137,137,3635,Bernardo Silva,26,2080,2,3.599,6,4.823,28,27,5,0,F M S,Manchester City,2,3.599,17.112,10.654
138,138,4490,Semi Ajayi,33,2773,2,1.734,0,0.510,13,7,3,1,D S,West Bromwich Albion,2,1.734,4.629,3.112
139,139,5584,Aaron Wan-Bissaka,34,3060,2,0.932,4,2.548,7,31,3,0,D,Manchester United,2,0.932,12.242,9.676
140,140,5613,Gabriel,22,1904,2,1.551,0,0.056,15,2,2,1,D S,Arsenal,2,1.551,5.588,5.574
141,141,6027,Jairo Riedewald,33,1803,2,0.563,0,0.897,8,11,4,0,M S,Crystal Palace,2,0.563,3.511,2.334
142,142,6049,Solly March,21,1684,2,1.784,1,1.679,22,27,0,0,D M S,Brighton,2,1.784,8.322,5.681
143,143,6063,Jacob Murphy,26,1611,2,1.491,3,3.433,30,19,3,0,D M S,Newcastle United,2,1.491,8.044,4.102
144,144,6157,Timothy Castagne,27,2349,2,1.600,3,2.307,8,21,1,0,D M,Leicester,2,1.600,8.446,6.606
145,145,6456,Callum Hudson-Odoi,23,1048,2,1.370,3,3.104,23,31,0,0,D F M S,Chelsea,2,1.370,7.824,5.499
146,146,6482,Eddie Nketiah,17,405,2,2.022,1,0.742,12,8,0,0,F S,Arsenal,2,2.022,2.077,0.221
147,147,6521,Yerry Mina,24,1941,2,1.749,0,0.020,17,1,2,0,D S,Everton,2,1.749,4.313,4.213
148,148,6756,Dwight McNeil,35,3002,2,1.007,5,5.419,25,46,1,0,M S,Burnley,2,1.007,6.875,3.607
149,149,7230,Emile Smith-Rowe,19,1382,2,1.592,4,3.449,13,23,0,0,M S,Arsenal,2,1.592,9.202,5.455
150,150,7722,TrÃ©zÃ©guet,21,1175,2,3.979,1,2.148,35,13,0,0,F M S,Aston Villa,2,3.979,7.027,1.904
151,151,7726,Ezri Konsa Ngoyo,36,3192,2,3.292,0,0.093,22,2,3,0,D S,Aston Villa,2,3.292,3.430,3.382
152,152,7752,Gabriel Martinelli,13,577,2,3.252,1,1.746,20,9,0,0,F M S,Arsenal,2,3.252,6.160,1.757
153,153,7753,James Justin,23,2070,2,1.517,1,2.059,9,19,4,0,D,Leicester,2,1.517,7.666,5.505
154,154,7991,Aaron Connolly,16,755,2,4.412,1,0.150,22,5,0,0,F M S,Brighton,2,4.412,4.721,0.191
155,155,8722,Ezgjan Alioski,36,2475,2,1.747,3,3.333,25,28,7,0,D M S,Leeds,2,1.747,13.478,9.686
156,156,8992,Hakim Ziyech,23,1182,2,1.987,3,4.478,35,34,3,0,F M S,Chelsea,2,1.987,7.661,3.692
157,157,9040,Conor Gallagher,30,2529,2,1.542,2,1.418,29,21,11,0,M S,West Bromwich Albion,2,1.542,5.060,3.125
158,158,9205,Jayden Bogle,16,1109,2,1.915,0,0.209,17,4,2,0,D M S,Sheffield United,2,1.915,2.669,1.366
159,159,76,Fabian SchÃ¤r,18,1252,1,1.461,0,0.000,12,0,4,1,D S,Newcastle United,0,0.699,0.955,0.874
160,160,204,Granit Xhaka,30,2447,1,0.712,2,1.334,18,14,7,1,D M S,Arsenal,1,0.712,13.537,12.522
161,161,229,Thiago AlcÃ¡ntara,24,1865,1,1.211,0,2.555,22,30,4,0,M S,Liverpool,1,1.211,11.153,9.468
162,162,332,Joel Matip,10,701,1,0.784,2,1.180,5,3,2,0,D S,Liverpool,1,0.784,4.383,4.383
163,163,486,Adam Lallana,29,1528,1,1.614,1,2.629,22,25,0,0,F M S,Brighton,1,1.614,9.720,5.874
164,164,492,HÃ©ctor BellerÃ­n,25,2098,1,0.860,2,2.172,15,21,8,0,D S,Arsenal,1,0.860,8.060,6.267
165,165,496,Mohamed Elneny,23,1540,1,0.476,0,0.257,9,4,3,0,M S,Arsenal,1,0.476,5.196,4.651
166,166,500,Alex Iwobi,29,1505,1,0.844,2,2.155,15,16,0,0,D F M S,Everton,1,0.844,7.219,4.476
167,167,512,Scott Dann,15,1350,1,0.548,0,0.018,4,1,1,0,D,Crystal Palace,1,0.548,1.185,1.168
168,168,532,Cheikhou KouyatÃ©,36,3126,1,0.824,0,0.831,7,8,4,0,D M S,Crystal Palace,1,0.824,4.744,4.531
169,169,535,Manuel Lanzini,17,548,1,0.971,1,1.002,12,11,1,0,M S,West Ham,1,0.971,3.233,1.580
170,170,537,Andy Carroll,18,369,1,0.603,0,0.063,13,2,1,0,F S,Newcastle United,1,0.603,0.989,0.542
171,171,579,Nathan AkÃ©,10,802,1,0.505,0,0.017,3,1,4,0,D S,Manchester City,1,0.505,4.211,4.194
172,172,605,Jordan Henderson,21,1710,1,1.136,1,1.484,14,14,0,0,D M S,Liverpool,1,1.136,11.494,10.461
173,173,638,Kyle Walker,23,1854,1,0.204,1,0.500,10,8,1,0,D S,Manchester City,1,0.204,9.923,9.525
174,174,639,Toby Alderweireld,25,2243,1,0.614,0,0.968,10,8,2,0,D,Tottenham,1,0.614,5.901,5.857
175,175,644,Erik Lamela,23,683,1,1.289,0,0.806,21,8,4,1,F M S,Tottenham,1,1.289,4.192,2.829
176,176,672,Jordan Ayew,33,2097,1,2.582,3,0.822,26,13,4,0,F M S,Crystal Palace,1,2.582,5.268,2.651
177,177,681,CÃ©sar Azpilicueta,26,2189,1,0.503,2,2.575,11,27,5,1,D S,Chelsea,1,0.503,13.989,12.339
178,178,688,Ruben Loftus-Cheek,31,1988,1,3.330,0,1.245,35,17,3,0,F M S,"Chelsea,Fulham",1,3.330,7.615,3.747
179,179,699,Gary Cahill,20,1800,1,0.737,1,0.622,11,8,3,0,D,Crystal Palace,1,0.737,2.273,2.023
180,180,700,Willian,25,1413,1,1.835,5,3.592,20,32,0,0,F M S,Arsenal,1,1.835,7.110,3.816
181,181,743,Dwight Gayle,18,483,1,2.930,1,0.276,16,6,0,0,F S,Newcastle United,1,2.930,3.038,0.514
182,182,753,Marc Albrighton,31,1731,1,1.247,5,4.036,21,38,2,0,D M S,Leicester,1,1.247,8.018,5.143
183,183,759,Daniel Amartey,12,714,1,0.542,0,0.000,3,0,2,0,D S,Leicester,1,0.542,2.532,2.457
184,184,769,Jonjo Shelvey,30,2617,1,2.453,3,2.626,42,37,7,0,M S,Newcastle United,1,2.453,9.464,7.526
185,185,775,Andros Townsend,34,2255,1,2.472,5,4.146,36,40,0,0,F M S,Crystal Palace,1,2.472,7.262,3.630
186,186,789,Robbie Brady,19,1061,1,0.783,1,0.909,16,7,3,0,M S,Burnley,1,0.783,2.678,1.531
187,187,833,Virgil van Dijk,5,370,1,0.553,0,0.000,4,0,1,0,D,Liverpool,1,0.553,1.410,1.288
188,188,842,Oriol Romeu,20,1748,1,0.446,1,1.537,14,14,6,0,M,Southampton,1,0.446,6.116,4.941
189,189,844,Jay Rodriguez,30,1220,1,2.851,2,1.211,30,6,3,0,F M S,Burnley,1,2.851,4.232,0.913
190,190,853,Paul Dummett,15,1254,1,0.444,0,0.229,3,4,2,0,D S,Newcastle United,1,0.444,3.160,2.979
191,191,875,Ciaran Clark,22,1895,1,0.662,0,0.144,8,2,3,0,D S,Newcastle United,1,0.662,2.863,2.863
192,192,966,Alex Oxlade-Chamberlain,13,238,1,0.301,1,0.302,8,2,0,0,F M S,Liverpool,1,0.301,0.999,0.767
193,193,985,Mason Holgate,27,2208,1,1.298,0,0.555,5,7,8,0,D M S,Everton,1,1.298,3.671,3.229
194,194,1006,Luke Shaw,32,2659,1,0.693,5,6.472,11,72,8,0,D S,Manchester United,1,0.693,12.844,10.096
195,195,1014,Tyler Roberts,27,1334,1,1.885,2,2.529,26,15,3,0,F M S,Leeds,1,1.885,7.462,3.504
196,196,1053,Keinan Davis,15,240,1,1.269,1,0.685,9,6,0,0,F S,Aston Villa,1,1.269,1.965,0.335
197,197,1234,Dennis Praet,15,730,1,0.439,1,1.216,8,7,0,0,M S,Leicester,1,0.439,2.112,1.292
198,198,1257,Alisson,33,2970,1,0.108,0,0.000,1,0,1,0,GK,Liverpool,1,0.108,3.559,3.559
199,199,1299,Mario Lemina,28,1706,1,1.244,0,1.126,19,12,5,0,D M S,Fulham,1,1.244,4.953,3.295
200,200,1545,Emil Krafth,16,1297,1,0.151,0,0.435,7,6,4,0,D S,Newcastle United,1,0.151,3.911,3.427
201,201,1652,Matthew Lowton,33,2970,1,0.759,1,2.772,21,26,5,0,D,Burnley,1,0.759,6.349,3.562
202,202,1665,James Tarkowski,35,3150,1,2.974,0,0.944,22,12,6,0,D,Burnley,1,2.974,3.004,2.816
203,203,1676,David Luiz,20,1410,1,0.670,0,0.524,15,2,1,1,D S,Arsenal,1,0.670,4.750,4.629

In [15]:
# reset kalau tidak mau terlihat semuanya

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [17]:
df

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.175,14,7.577,138,49,1,0,F,Tottenham,19,19.130,24.996,4.451
1,1,1250,Mohamed Salah,37,3085,22,20.251,5,6.529,126,55,0,0,F M S,Liverpool,16,15.684,28.968,9.800
2,2,1228,Bruno Fernandes,37,3117,18,16.019,12,11.475,121,95,6,0,M S,Manchester United,9,8.408,26.911,11.932
3,3,453,Son Heung-Min,37,3139,17,11.023,10,9.513,68,75,0,0,F M S,Tottenham,16,10.262,20.672,6.609
4,4,822,Patrick Bamford,38,3085,17,18.402,7,3.782,107,30,3,0,F S,Leeds,15,16.880,23.395,4.132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,517,9415,Jaden Philogene-Bidace,1,1,0,0.000,0,0.000,0,0,0,0,S,Aston Villa,0,0.000,0.056,0.056
518,518,9423,Gaetano Berardi,2,113,0,0.075,0,0.000,1,0,0,0,D S,Leeds,0,0.075,0.231,0.231
519,519,9524,Anthony Elanga,1,67,0,0.000,0,0.000,0,0,0,0,M,Manchester United,0,0.000,0.000,0.000
520,520,9540,Femi Seriki,1,1,0,0.000,0,0.000,0,0,0,0,S,Sheffield United,0,0.000,0.000,0.000
521,521,9552,Tyrese Francois,1,13,0,0.000,0,0.000,0,0,0,0,S,Fulham,0,0.000,0.000,0.000

In [19]:
# menghapus unnamed (dilebur bersama index krn sama saja)

dfnew = pd.read_csv("epl-goalScorer(20-21).csv", index_col = 0)
dfnew

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,647,Harry Kane,35,3097,23,22.175,14,7.577,138,49,1,0,F,Tottenham,19,19.130,24.996,4.451
1,1250,Mohamed Salah,37,3085,22,20.251,5,6.529,126,55,0,0,F M S,Liverpool,16,15.684,28.968,9.800
2,1228,Bruno Fernandes,37,3117,18,16.019,12,11.475,121,95,6,0,M S,Manchester United,9,8.408,26.911,11.932
3,453,Son Heung-Min,37,3139,17,11.023,10,9.513,68,75,0,0,F M S,Tottenham,16,10.262,20.672,6.609
4,822,Patrick Bamford,38,3085,17,18.402,7,3.782,107,30,3,0,F S,Leeds,15,16.880,23.395,4.132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,9415,Jaden Philogene-Bidace,1,1,0,0.000,0,0.000,0,0,0,0,S,Aston Villa,0,0.000,0.056,0.056
518,9423,Gaetano Berardi,2,113,0,0.075,0,0.000,1,0,0,0,D S,Leeds,0,0.075,0.231,0.231
519,9524,Anthony Elanga,1,67,0,0.000,0,0.000,0,0,0,0,M,Manchester United,0,0.000,0.000,0.000
520,9540,Femi Seriki,1,1,0,0.000,0,0.000,0,0,0,0,S,Sheffield United,0,0.000,0.000,0.000
521,9552,Tyrese Francois,1,13,0,0.000,0,0.000,0,0,0,0,S,Fulham,0,0.000,0.000,0.000

In [21]:
# melihat 3 data paling atas

dfnew.head(5)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,647,Harry Kane,35,3097,23,22.175,14,7.577,138,49,1,0,F,Tottenham,19,19.130,24.996,4.451
1,1250,Mohamed Salah,37,3085,22,20.251,5,6.529,126,55,0,0,F M S,Liverpool,16,15.684,28.968,9.800
2,1228,Bruno Fernandes,37,3117,18,16.019,12,11.475,121,95,6,0,M S,Manchester United,9,8.408,26.911,11.932
3,453,Son Heung-Min,37,3139,17,11.023,10,9.513,68,75,0,0,F M S,Tottenham,16,10.262,20.672,6.609
4,822,Patrick Bamford,38,3085,17,18.402,7,3.782,107,30,3,0,F S,Leeds,15,16.880,23.395,4.132

In [24]:
# melihat 3 data terakhir

dfnew.tail(3)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
519,9524,Anthony Elanga,1,67,0,0.0,0,0.0,0,0,0,0,M,Manchester United,0,0.0,0.0,0.0
520,9540,Femi Seriki,1,1,0,0.0,0,0.0,0,0,0,0,S,Sheffield United,0,0.0,0.0,0.0
521,9552,Tyrese Francois,1,13,0,0.0,0,0.0,0,0,0,0,S,Fulham,0,0.0,0.0,0.0

## B. Exploratory Data Analysis Non Graphical
### Univariate Non-graphical EDA

**1. Mengetahui Tipe Data**

In [25]:
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 522 entries, 0 to 521
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            522 non-null    int64
 1   player_name   522 non-null    object
 2   games         522 non-null    int64
 3   time          522 non-null    int64
 4   goals         522 non-null    int64
 5   xG            522 non-null    float64
 6   assists       522 non-null    int64
 7   xA            522 non-null    float64
 8   shots         522 non-null    int64
 9   key_passes    522 non-null    int64
 10  yellow_cards  522 non-null    int64
 11  red_cards     522 non-null    int64
 12  position      522 non-null    object
 13  team_title    522 non-null    object
 14  npg           522 non-null    int64
 15  npxG          522 non-null    float64
 16  xGChain       522 non-null    float64
 17  xGBuildup     522 non-null    float64
dtypes: float64(5), int64(10), object(3)
memory usage: 77.5+ KB

**2. Mengubah Type Data**

In [26]:
dfnew = dfnew.astype({'id': 'object'})

In [28]:
dfnew.dtypes

id               object
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object

**3. Mengetahui apakah ada Missing Value / NaN**

In [29]:
dfnew.isna().sum()

id              0
player_name     0
games           0
time            0
goals           0
xG              0
assists         0
xA              0
shots           0
key_passes      0
yellow_cards    0
red_cards       0
position        0
team_title      0
npg             0
npxG            0
xGChain         0
xGBuildup       0
dtype: int64

**4. Mengetahui apakah ada duplicated data**

In [30]:
dfnew.duplicated().sum()

0

In [31]:
dfnew.drop_duplicates(keep = 'first')

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,647,Harry Kane,35,3097,23,22.175,14,7.577,138,49,1,0,F,Tottenham,19,19.130,24.996,4.451
1,1250,Mohamed Salah,37,3085,22,20.251,5,6.529,126,55,0,0,F M S,Liverpool,16,15.684,28.968,9.800
2,1228,Bruno Fernandes,37,3117,18,16.019,12,11.475,121,95,6,0,M S,Manchester United,9,8.408,26.911,11.932
3,453,Son Heung-Min,37,3139,17,11.023,10,9.513,68,75,0,0,F M S,Tottenham,16,10.262,20.672,6.609
4,822,Patrick Bamford,38,3085,17,18.402,7,3.782,107,30,3,0,F S,Leeds,15,16.880,23.395,4.132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,9415,Jaden Philogene-Bidace,1,1,0,0.000,0,0.000,0,0,0,0,S,Aston Villa,0,0.000,0.056,0.056
518,9423,Gaetano Berardi,2,113,0,0.075,0,0.000,1,0,0,0,D S,Leeds,0,0.075,0.231,0.231
519,9524,Anthony Elanga,1,67,0,0.000,0,0.000,0,0,0,0,M,Manchester United,0,0.000,0.000,0.000
520,9540,Femi Seriki,1,1,0,0.000,0,0.000,0,0,0,0,S,Sheffield United,0,0.000,0.000,0.000
521,9552,Tyrese Francois,1,13,0,0.000,0,0.000,0,0,0,0,S,Fulham,0,0.000,0.000,0.000

**5. Mencoba untuk Seleksi Rows / Columns**
- format `.iloc[rows yang ingin diseleksi, kolom yang ingin diseleksi]`

In [32]:
# single row

dfnew.iloc[0, :]

id                     647
player_name     Harry Kane
games                   35
time                  3097
goals                   23
xG                    22.2
assists                 14
xA                    7.58
shots                  138
key_passes              49
yellow_cards             1
red_cards                0
position                 F
team_title       Tottenham
npg                     19
npxG                  19.1
xGChain                 25
xGBuildup             4.45
Name: 0, dtype: object

In [33]:
# multiple rows
# memilih baris 46-51 dan semua kolom

dfnew.iloc[46:51, :]

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
46,6441,FerrÃ¡n Torres,23,1291,7,5.729,2,2.202,36,18,1,0,F M S,Manchester City,7,5.729,9.769,2.724
47,7490,Mason Greenwood,31,1825,7,6.976,2,2.428,67,14,2,0,F M S,Manchester United,7,6.976,14.032,5.954
48,7711,David McGoldrick,34,2319,7,7.383,1,1.050,65,16,7,0,F M S,Sheffield United,7,7.383,9.682,3.188
49,65,Timo Werner,35,2605,6,13.433,8,6.667,80,36,2,0,F M S,Chelsea,6,13.433,20.533,5.242
50,501,Danny Welbeck,24,1551,6,7.380,1,3.231,35,22,0,0,F M S,Brighton,6,6.619,10.266,1.477

In [34]:
# multiple columns
# memilih semua baris, tetapi hanya kolom nomor 2 sampai terakhir

dfnew.iloc[:, 2:]

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,35,3097,23,22.175,14,7.577,138,49,1,0,F,Tottenham,19,19.130,24.996,4.451
1,37,3085,22,20.251,5,6.529,126,55,0,0,F M S,Liverpool,16,15.684,28.968,9.800
2,37,3117,18,16.019,12,11.475,121,95,6,0,M S,Manchester United,9,8.408,26.911,11.932
3,37,3139,17,11.023,10,9.513,68,75,0,0,F M S,Tottenham,16,10.262,20.672,6.609
4,38,3085,17,18.402,7,3.782,107,30,3,0,F S,Leeds,15,16.880,23.395,4.132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,1,1,0,0.000,0,0.000,0,0,0,0,S,Aston Villa,0,0.000,0.056,0.056
518,2,113,0,0.075,0,0.000,1,0,0,0,D S,Leeds,0,0.075,0.231,0.231
519,1,67,0,0.000,0,0.000,0,0,0,0,M,Manchester United,0,0.000,0.000,0.000
520,1,1,0,0.000,0,0.000,0,0,0,0,S,Sheffield United,0,0.000,0.000,0.000
521,1,13,0,0.000,0,0.000,0,0,0,0,S,Fulham,0,0.000,0.000,0.000

In [29]:
# multiple columns 
# memilih semua baris tapi hanya kolom 0-2

dfnew.iloc[:, 0:3]

       id             player_name  games
0     647              Harry Kane     35
1    1250           Mohamed Salah     37
2    1228         Bruno Fernandes     37
3     453           Son Heung-Min     37
4     822         Patrick Bamford     38
..    ...                     ...    ...
517  9415  Jaden Philogene-Bidace      1
518  9423         Gaetano Berardi      2
519  9524          Anthony Elanga      1
520  9540             Femi Seriki      1
521  9552         Tyrese Francois      1

[522 rows x 3 columns]

**4. Mencoba Filter Rows & Columns dengan Kriteria**
- format `.loc[rows sesuai kriteria, columns]`

In [35]:
# mencari pemain yang goals nya >= 6

dfnew.loc[(dfnew['goals'] >= 6), 'player_name']

0                    Harry Kane
1                 Mohamed Salah
2               Bruno Fernandes
3                 Son Heung-Min
4               Patrick Bamford
5         Dominic Calvert-Lewin
6                   Jamie Vardy
7                 Ollie Watkins
8                Ilkay GÃ¼ndogan
9           Alexandre Lacazette
10                Callum Wilson
11            Kelechi Iheanacho
12                   Danny Ings
13                   Chris Wood
14                Wilfried Zaha
15              Marcus Rashford
16                   Sadio ManÃ©
17                  Gareth Bale
18              Matheus Pereira
19    Pierre-Emerick Aubameyang
20              Michail Antonio
21            Christian Benteke
22              Raheem Sterling
23               Edinson Cavani
24               Anwar El Ghazi
25                 Tomas Soucek
26              Roberto Firmino
27                Jesse Lingard
28                 Riyad Mahrez
29                Harvey Barnes
30                   Diogo Jota
31                    Che Adams
32            James Ward-Prowse
33                 Jarrod Bowen
34                  Neal Maupay
35                Gabriel Jesus
36                 Nicolas Pepe
37                   Phil Foden
38                  Joe Willock
39               James Maddison
40                Stuart Dallas
41                Jack Harrison
42              Bertrand TraorÃ©
43                     Jorginho
44                      Rodrigo
45                  Richarlison
46                FerrÃ¡n Torres
47              Mason Greenwood
48             David McGoldrick
49                  Timo Werner
50                Danny Welbeck
51                Jack Grealish
52                Tammy Abraham
53             Gylfi Sigurdsson
54              James RodrÃ­guez
55              Youri Tielemans
56                  Mason Mount
57                     Raphinha
Name: player_name, dtype: object

In [36]:
# mencari pemain & tim yang goals nya >= 6 dan assist <= 7

dfnew.loc[(dfnew['goals'] >= 6) & (dfnew['assists'] <= 7), ['player_name', 'team_title']]

                  player_name                team_title
1               Mohamed Salah                 Liverpool
4             Patrick Bamford                     Leeds
5       Dominic Calvert-Lewin                   Everton
7               Ollie Watkins               Aston Villa
8              Ilkay GÃ¼ndogan           Manchester City
9         Alexandre Lacazette                   Arsenal
10              Callum Wilson          Newcastle United
11          Kelechi Iheanacho                 Leicester
12                 Danny Ings               Southampton
13                 Chris Wood                   Burnley
14              Wilfried Zaha            Crystal Palace
16                 Sadio ManÃ©                 Liverpool
17                Gareth Bale                 Tottenham
18            Matheus Pereira      West Bromwich Albion
19  Pierre-Emerick Aubameyang                   Arsenal
20            Michail Antonio                  West Ham
21          Christian Benteke            Crystal Palace
22            Raheem Sterling           Manchester City
23             Edinson Cavani         Manchester United
24             Anwar El Ghazi               Aston Villa
25               Tomas Soucek                  West Ham
26            Roberto Firmino                 Liverpool
27              Jesse Lingard                  West Ham
28               Riyad Mahrez           Manchester City
29              Harvey Barnes                 Leicester
30                 Diogo Jota                 Liverpool
31                  Che Adams               Southampton
32          James Ward-Prowse               Southampton
33               Jarrod Bowen                  West Ham
34                Neal Maupay                  Brighton
35              Gabriel Jesus           Manchester City
36               Nicolas Pepe                   Arsenal
37                 Phil Foden           Manchester City
38                Joe Willock  Arsenal,Newcastle United
39             James Maddison                 Leicester
40              Stuart Dallas                     Leeds
42            Bertrand TraorÃ©               Aston Villa
43                   Jorginho                   Chelsea
44                    Rodrigo                     Leeds
45                Richarlison                   Everton
46              FerrÃ¡n Torres           Manchester City
47            Mason Greenwood         Manchester United
48           David McGoldrick          Sheffield United
50              Danny Welbeck                  Brighton
52              Tammy Abraham                   Chelsea
53           Gylfi Sigurdsson                   Everton
54            James RodrÃ­guez                   Everton
55            Youri Tielemans                 Leicester
56                Mason Mount                   Chelsea

In [37]:
baris = (dfnew['goals'] >= 6) & (dfnew['assists'] <= 7)
kolom = ['player_name', 'team_title']

df.loc[baris, kolom]

                  player_name                team_title
1               Mohamed Salah                 Liverpool
4             Patrick Bamford                     Leeds
5       Dominic Calvert-Lewin                   Everton
7               Ollie Watkins               Aston Villa
8              Ilkay GÃ¼ndogan           Manchester City
9         Alexandre Lacazette                   Arsenal
10              Callum Wilson          Newcastle United
11          Kelechi Iheanacho                 Leicester
12                 Danny Ings               Southampton
13                 Chris Wood                   Burnley
14              Wilfried Zaha            Crystal Palace
16                 Sadio ManÃ©                 Liverpool
17                Gareth Bale                 Tottenham
18            Matheus Pereira      West Bromwich Albion
19  Pierre-Emerick Aubameyang                   Arsenal
20            Michail Antonio                  West Ham
21          Christian Benteke            Crystal Palace
22            Raheem Sterling           Manchester City
23             Edinson Cavani         Manchester United
24             Anwar El Ghazi               Aston Villa
25               Tomas Soucek                  West Ham
26            Roberto Firmino                 Liverpool
27              Jesse Lingard                  West Ham
28               Riyad Mahrez           Manchester City
29              Harvey Barnes                 Leicester
30                 Diogo Jota                 Liverpool
31                  Che Adams               Southampton
32          James Ward-Prowse               Southampton
33               Jarrod Bowen                  West Ham
34                Neal Maupay                  Brighton
35              Gabriel Jesus           Manchester City
36               Nicolas Pepe                   Arsenal
37                 Phil Foden           Manchester City
38                Joe Willock  Arsenal,Newcastle United
39             James Maddison                 Leicester
40              Stuart Dallas                     Leeds
42            Bertrand TraorÃ©               Aston Villa
43                   Jorginho                   Chelsea
44                    Rodrigo                     Leeds
45                Richarlison                   Everton
46              FerrÃ¡n Torres           Manchester City
47            Mason Greenwood         Manchester United
48           David McGoldrick          Sheffield United
50              Danny Welbeck                  Brighton
52              Tammy Abraham                   Chelsea
53           Gylfi Sigurdsson                   Everton
54            James RodrÃ­guez                   Everton
55            Youri Tielemans                 Leicester
56                Mason Mount                   Chelsea

**6. Mencoba Sorting Data (ascending/descending)**

In [38]:
# sorting nama pemain

dfnew.sort_values('player_name', ascending = True)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
154,7991,Aaron Connolly,16,755,2,4.412,1,0.150,22,5,0,0,F M S,Brighton,2,4.412,4.721,0.191
281,534,Aaron Cresswell,35,3086,0,0.883,8,7.347,19,57,3,0,D,West Ham,0,0.883,10.610,8.382
390,5603,Aaron Ramsdale,37,3330,0,0.000,0,0.054,0,1,1,0,GK,Sheffield United,0,0.000,2.795,2.741
139,5584,Aaron Wan-Bissaka,34,3060,2,0.932,4,2.548,7,31,3,0,D,Manchester United,2,0.932,12.242,9.676
126,1726,Abdoulaye DoucourÃ©,28,2409,2,2.370,3,2.382,18,20,6,0,M,Everton,2,2.370,10.356,6.734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,7280,Yan Valery,3,95,0,0.293,0,0.092,2,1,0,0,D S,Southampton,0,0.293,0.470,0.177
147,6521,Yerry Mina,24,1941,2,1.749,0,0.020,17,1,2,0,D S,Everton,2,1.749,4.313,4.213
55,5956,Youri Tielemans,38,3359,6,4.168,4,3.312,48,49,6,0,M S,Leicester,4,2.646,18.975,14.945
218,5609,Yves Bissouma,35,3031,1,1.056,0,1.081,41,16,8,1,M S,Brighton,1,1.056,9.618,8.110
452,7817,Zack Steffen,1,90,0,0.000,0,0.000,0,0,0,0,GK,Manchester City,0,0.000,0.350,0.350

In [33]:
# sorting nama games dan time 

dfnew.sort_values(['games', 'time'], ascending = True)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
277,525,Martin Kelly,1,1,0,0.000,0,0.000,0,0,0,0,S,Crystal Palace,0,0.000,0.000,0.000
406,6350,Jayson Molumby,1,1,0,0.000,0,0.000,0,0,0,0,S,Brighton,0,0.000,0.000,0.000
512,9332,Dane Scarlett,1,1,0,0.000,0,0.000,0,0,0,0,S,Tottenham,0,0.000,0.000,0.000
514,9359,Shola Shoretire,1,1,0,0.000,0,0.000,0,0,0,0,S,Manchester United,0,0.000,0.000,0.000
516,9406,Nathan Broadhead,1,1,0,0.000,0,0.000,0,0,0,0,S,Everton,0,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,8718,Stuart Dallas,38,3412,8,4.457,2,2.085,48,26,7,0,D M,Leeds,8,4.457,18.534,13.810
110,343,Pierre-Emile HÃ¸jbjerg,38,3420,2,1.138,4,1.756,14,16,9,0,M,Tottenham,2,1.138,16.206,14.680
296,637,Hugo Lloris,38,3420,0,0.000,0,0.000,0,0,0,0,GK,Tottenham,0,0.000,4.801,4.801
311,745,Kasper Schmeichel,38,3420,0,0.000,0,0.000,0,0,0,0,GK,Leicester,0,0.000,3.869,3.869
378,4401,Emiliano Martinez,38,3420,0,0.000,0,0.123,0,2,1,0,GK,Aston Villa,0,0.000,3.731,3.608

**7. Menghitung Frekuensi Elemen Data Kategori (Tabulasi Frekuensi)**

In [41]:
dfnew['team_title'].value_counts()

Everton                          28
West Bromwich Albion             28
Sheffield United                 27
Leicester                        27
Liverpool                        27
Wolverhampton Wanderers          27
Manchester United                27
Southampton                      27
Fulham                           27
Newcastle United                 26
Arsenal                          26
Brighton                         26
Chelsea                          25
Burnley                          25
Manchester City                  24
Crystal Palace                   24
Tottenham                        24
Aston Villa                      23
Leeds                            23
West Ham                         23
Arsenal,Brighton                  1
Aston Villa,Chelsea               1
Arsenal,West Bromwich Albion      1
Chelsea,Fulham                    1
West Bromwich Albion,West Ham     1
Everton,Southampton               1
Liverpool,Southampton             1
Arsenal,Newcastle United          1
Name: team_title, dtype: int64

## Multivariate Non-graphical EDA

**1. Menghitung Statistik Deskriptif pada Data**

In [42]:
# khusus tipe data numerik

dfnew.describe()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
count,522.000,522.000,522.000,522.000,522.000,522.000,522.000,522.000,522.000,522.000,522.000,522.000,522.000,522.000
mean,19.644,1420.069,1.862,2.001,1.289,1.376,17.379,12.964,2.061,0.092,1.669,1.821,5.663,3.455
std,11.620,1031.605,3.339,3.318,2.083,1.887,21.573,16.164,2.204,0.296,2.910,2.931,5.600,3.377
min,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,10.000,470.250,0.000,0.075,0.000,0.049,2.000,1.000,0.000,0.000,0.000,0.075,1.191,0.720
50%,21.000,1342.000,1.000,0.737,0.000,0.691,10.000,7.000,2.000,0.000,0.500,0.716,4.253,2.656
75%,30.000,2319.000,2.000,2.053,2.000,2.051,23.750,19.000,3.000,0.000,2.000,1.946,8.308,5.255
max,38.000,3420.000,23.000,22.175,14.000,11.475,138.000,95.000,12.000,2.000,19.000,19.130,28.968,18.323

In [43]:
# khusus tipe data kategorikal

dfnew.describe(include = 'object')

          id player_name position team_title
count    522         522      522        522
unique   522         522       14         28
top     8865   Issa Diop      M S    Everton
freq       1           1      106         28

**2. Menghitung Statistik pada setiap Kolom**

In [44]:
dfnew.mean()

id              4380.933
games             19.644
time            1420.069
goals              1.862
xG                 2.001
assists            1.289
xA                 1.376
shots             17.379
key_passes        12.964
yellow_cards       2.061
red_cards          0.092
npg                1.669
npxG               1.821
xGChain            5.663
xGBuildup          3.455
dtype: float64

In [45]:
dfnew.sum()

id                                                        2286847
player_name     Harry KaneMohamed SalahBruno FernandesSon Heun...
games                                                       10254
time                                                       741276
goals                                                         972
xG                                                       1.04e+03
assists                                                       673
xA                                                            718
shots                                                        9072
key_passes                                                   6767
yellow_cards                                                 1076
red_cards                                                      48
position        FF M SM SF M SF SF SF SFM SF M SF SF SF SF SF ...
team_title      TottenhamLiverpoolManchester UnitedTottenhamLe...
npg                                                           871
npxG                                                          951
xGChain                                                  2.96e+03
xGBuildup                                                 1.8e+03
dtype: object

In [46]:
dfnew.median()

id              4627.000
games             21.000
time            1342.000
goals              1.000
xG                 0.737
assists            0.000
xA                 0.691
shots             10.000
key_passes         7.000
yellow_cards       2.000
red_cards          0.000
npg                0.500
npxG               0.716
xGChain            4.253
xGBuildup          2.656
dtype: float64

In [47]:
dfnew.std()

id              3281.776
games             11.620
time            1031.605
goals              3.339
xG                 3.318
assists            2.083
xA                 1.887
shots             21.573
key_passes        16.164
yellow_cards       2.204
red_cards          0.296
npg                2.910
npxG               2.931
xGChain            5.600
xGBuildup          3.377
dtype: float64

In [48]:
dfnew.quantile(0.75)

games             30.000
time            2319.000
goals              2.000
xG                 2.053
assists            2.000
xA                 2.051
shots             23.750
key_passes        19.000
yellow_cards       3.000
red_cards          0.000
npg                2.000
npxG               1.946
xGChain            8.308
xGBuildup          5.255
Name: 0.75, dtype: float64

**9. Mendeteksi Outlier Menggunakan Rumus Tukey's Fences IQR (Spread)**

Data dianggap sebagai `outliers` apabila :

$$ < (Q1 - 1.5 \times IQR) $$
$$ atau $$
$$ > (Q3 - 1.5 \times IQR) $$

Rumus IQR (Interquartile) :
$$ IQR = Q3-Q1 $$

In [49]:
q1 = dfnew.quantile(0.25) # minimum
q3 = dfnew.quantile(0.75) # maximum
iqr = q3 - q1
iqr

games             20.000
time            1848.750
goals              2.000
xG                 1.979
assists            2.000
xA                 2.001
shots             21.750
key_passes        18.000
yellow_cards       3.000
red_cards          0.000
npg                2.000
npxG               1.871
xGChain            7.117
xGBuildup          4.534
dtype: float64

In [50]:
outlier_criteria = (dfnew < (q1-1.5*iqr)) | (dfnew > (q3+1.5*iqr))
outlier_criteria

,assists,games,goals,id,key_passes,npg,npxG,player_name,position,red_cards,shots,team_title,time,xA,xG,xGBuildup,xGChain,yellow_cards
0,True,False,True,False,True,True,True,False,False,False,True,False,False,True,True,False,True,False
1,False,False,True,False,True,True,True,False,False,False,True,False,False,True,True,False,True,False
2,True,False,True,False,True,True,True,False,False,False,True,False,False,True,True,False,True,False
3,True,False,True,False,True,True,True,False,False,False,True,False,False,True,True,False,True,False
4,True,False,True,False,False,True,True,False,False,False,True,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
518,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
519,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
520,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
521,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [51]:
outlier_criteria.sum()

assists         27
games            0
goals           58
id               0
key_passes      24
npg             52
npxG            62
player_name      0
position         0
red_cards       47
shots           36
team_title       0
time             0
xA              35
xG              70
xGBuildup       13
xGChain         20
yellow_cards    13
dtype: int64

In [52]:
# data yang outlier 

df_outlier = dfnew[outlier_criteria.any(axis=1)]
df_outlier

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,647,Harry Kane,35,3097,23,22.175,14,7.577,138,49,1,0,F,Tottenham,19,19.130,24.996,4.451
1,1250,Mohamed Salah,37,3085,22,20.251,5,6.529,126,55,0,0,F M S,Liverpool,16,15.684,28.968,9.800
2,1228,Bruno Fernandes,37,3117,18,16.019,12,11.475,121,95,6,0,M S,Manchester United,9,8.408,26.911,11.932
3,453,Son Heung-Min,37,3139,17,11.023,10,9.513,68,75,0,0,F M S,Tottenham,16,10.262,20.672,6.609
4,822,Patrick Bamford,38,3085,17,18.402,7,3.782,107,30,3,0,F S,Leeds,15,16.880,23.395,4.132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,7708,John Lundstram,28,2034,0,1.876,2,1.460,20,20,8,1,M S,Sheffield United,0,1.115,7.169,5.259
476,8511,Alexandre Jankewitz,2,2,0,0.000,0,0.000,0,0,0,1,M S,Southampton,0,0.000,0.092,0.092
488,8864,Matthew Cash,28,2389,0,0.248,2,1.906,9,21,6,1,D,Aston Villa,0,0.248,6.592,5.033
493,8940,Antonee Robinson,28,2158,0,0.468,0,2.033,10,29,4,1,D M S,Fulham,0,0.468,7.803,6.396
495,8965,Vladimir Coufal,33,2966,0,1.399,6,6.037,15,44,3,0,D M,West Ham,0,1.399,14.375,8.325

In [53]:
# data yang tidak outlier 

df_no_outlier = dfnew[~outlier_criteria.any(axis=1)]
df_no_outlier

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
59,935,Kurt Zouma,24,2024,5,3.137,0,0.081,27,4,3,0,D S,Chelsea,5,3.137,6.216,6.133
60,4476,Callum Robinson,28,1580,5,3.203,0,1.050,31,16,0,0,F M S,West Bromwich Albion,5,3.203,5.217,1.596
63,6827,Bobby Reid,33,2394,5,4.270,2,1.310,34,14,7,0,D F M S,Fulham,5,4.270,8.203,3.131
72,4105,RaÃºl JimÃ©nez,10,824,4,2.361,0,0.633,26,6,0,0,F,Wolverhampton Wanderers,4,2.361,3.684,1.233
73,4381,Mateusz Klich,35,2404,4,3.000,5,3.651,36,44,6,0,M S,Leeds,2,1.478,14.608,10.386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,9415,Jaden Philogene-Bidace,1,1,0,0.000,0,0.000,0,0,0,0,S,Aston Villa,0,0.000,0.056,0.056
518,9423,Gaetano Berardi,2,113,0,0.075,0,0.000,1,0,0,0,D S,Leeds,0,0.075,0.231,0.231
519,9524,Anthony Elanga,1,67,0,0.000,0,0.000,0,0,0,0,M,Manchester United,0,0.000,0.000,0.000
520,9540,Femi Seriki,1,1,0,0.000,0,0.000,0,0,0,0,S,Sheffield United,0,0.000,0.000,0.000
521,9552,Tyrese Francois,1,13,0,0.000,0,0.000,0,0,0,0,S,Fulham,0,0.000,0.000,0.000

In [54]:
# memfilter assist dan pemain yang termasuk dalam outlier

dfnew.loc[:, ['player_name', 'assists']][outlier_criteria['assists']].sort_values(by = ['assists'], ascending = False)

                player_name  assists
0                Harry Kane       14
2           Bruno Fernandes       12
58          Kevin De Bruyne       11
3             Son Heung-Min       10
51            Jack Grealish       10
6               Jamie Vardy        9
15          Marcus Rashford        9
57                 Raphinha        9
41            Jack Harrison        8
281         Aaron Cresswell        8
83              Pascal GroÃŸ        8
49              Timo Werner        8
32        James Ward-Prowse        7
26          Roberto Firmino        7
16               Sadio ManÃ©        7
130  Trent Alexander-Arnold        7
204        Andrew Robertson        7
4           Patrick Bamford        7
358             Lucas Digne        7
42          Bertrand TraorÃ©        6
22          Raheem Sterling        6
18          Matheus Pereira        6
62               Pedro Neto        6
79             Eberechi Eze        6
137          Bernardo Silva        6
211           Said Benrahma        6
495         Vladimir Coufal        6

**10. Mencari Korelasi antar Columns**
- korelasi digunakan untuk analisis `data kuantitatif & data kuantitatif`
- interpretasi : semakin tinggi nilai korelasi, maka dapat dikatakan sebagai hubungan yang semakin kuat
> - -1 = hubungan yang berkebalikan 
> - 0 = tidak ada hubungan 
> - +1 = ada hubungan

In [57]:
dfnew.corr()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
games,1.000,0.945,0.440,0.464,0.504,0.563,0.599,0.618,0.566,0.160,0.437,0.466,0.727,0.697
time,0.945,1.000,0.399,0.411,0.474,0.517,0.530,0.575,0.592,0.186,0.393,0.408,0.704,0.731
goals,0.440,0.399,1.000,0.933,0.617,0.607,0.873,0.568,0.097,0.054,0.972,0.906,0.728,0.291
xG,0.464,0.411,0.933,1.000,0.636,0.627,0.910,0.570,0.094,0.049,0.894,0.979,0.764,0.283
assists,0.504,0.474,0.617,0.636,1.000,0.886,0.721,0.835,0.209,-0.021,0.587,0.616,0.753,0.473
xA,0.563,0.517,0.607,0.627,0.886,1.000,0.760,0.947,0.244,0.006,0.585,0.611,0.814,0.548
shots,0.599,0.530,0.873,0.910,0.721,0.760,1.000,0.743,0.250,0.074,0.853,0.901,0.843,0.448
key_passes,0.618,0.575,0.568,0.570,0.835,0.947,0.743,1.000,0.343,0.023,0.540,0.546,0.808,0.619
yellow_cards,0.566,0.592,0.097,0.094,0.209,0.244,0.250,0.343,1.000,0.165,0.093,0.089,0.402,0.562
red_cards,0.160,0.186,0.054,0.049,-0.021,0.006,0.074,0.023,0.165,1.000,0.056,0.047,0.104,0.168
npg,0.437,0.393,0.972,0.894,0.587,0.585,0.853,0.540,0.093,0.056,1.000,0.913,0.721,0.284
npxG,0.466,0.408,0.906,0.979,0.616,0.611,0.901,0.546,0.089,0.047,0.913,1.000,0.763,0.273
xGChain,0.727,0.704,0.728,0.764,0.753,0.814,0.843,0.808,0.402,0.104,0.721,0.763,1.000,0.802
xGBuildup,0.697,0.731,0.291,0.283,0.473,0.548,0.448,0.619,0.562,0.168,0.284,0.273,0.802,1.000

**11. Menggunakan GroupBy & Pivotable untuk Analisis per Kelompok**
- Group By dan Pivotable digunakan ketika ingin menganalisis `data kategori dan data kuantitatif` 
- Group By dan Pivotable digunakan ketika ingin menganalisis pada masing-masing kategori pada column, contoh : 
> - ingin mengetahui berapa rata-rata harga bensin pada tiap provinsi di indonesia 
> - ingin mengetahui rata-rata goals pada tiap tim

In [60]:
# single group 

dfnew.groupby('team_title')['goals'].mean().to_frame()

                               goals
team_title
Arsenal                        1.962
Arsenal,Brighton               0.000
Arsenal,Newcastle United       8.000
Arsenal,West Bromwich Albion   0.000
Aston Villa                    2.130
Aston Villa,Chelsea            3.000
Brighton                       1.500
Burnley                        1.280
Chelsea                        2.240
Chelsea,Fulham                 1.000
Crystal Palace                 1.625
Everton                        1.607
Everton,Southampton            3.000
Fulham                         0.926
Leeds                          2.609
Leicester                      2.370
Liverpool                      2.370
Liverpool,Southampton          3.000
Manchester City                3.208
Manchester United              2.519
Newcastle United               1.385
Sheffield United               0.667
Southampton                    1.556
Tottenham                      2.750
West Bromwich Albion           1.179
West Bromwich Albion,West Ham  0.000
West Ham                       2.478
Wolverhampton Wanderers        1.222

In [62]:
dfnew.pivot_table(values = 'goals', index = 'team_title', aggfunc = 'mean')

                               goals
team_title
Arsenal                        1.962
Arsenal,Brighton               0.000
Arsenal,Newcastle United       8.000
Arsenal,West Bromwich Albion   0.000
Aston Villa                    2.130
Aston Villa,Chelsea            3.000
Brighton                       1.500
Burnley                        1.280
Chelsea                        2.240
Chelsea,Fulham                 1.000
Crystal Palace                 1.625
Everton                        1.607
Everton,Southampton            3.000
Fulham                         0.926
Leeds                          2.609
Leicester                      2.370
Liverpool                      2.370
Liverpool,Southampton          3.000
Manchester City                3.208
Manchester United              2.519
Newcastle United               1.385
Sheffield United               0.667
Southampton                    1.556
Tottenham                      2.750
West Bromwich Albion           1.179
West Bromwich Albion,West Ham  0.000
West Ham                       2.478
Wolverhampton Wanderers        1.222

In [63]:
dfnew.groupby('team_title').mean()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
team_title,,,,,,,,,,,,,,
Arsenal,19.115,1365.538,1.962,2.006,1.385,1.356,16.769,11.962,1.769,0.192,1.731,1.830,6.585,4.226
"Arsenal,Brighton",14.000,1260.000,0.000,0.000,0.000,0.060,0.000,1.000,1.000,0.000,0.000,0.000,1.656,1.656
"Arsenal,Newcastle United",21.000,1215.000,8.000,5.088,0.000,0.734,23.000,10.000,1.000,0.000,8.000,4.327,7.007,2.988
"Arsenal,West Bromwich Albion",26.000,1719.000,0.000,0.796,0.000,0.822,12.000,6.000,2.000,0.000,0.000,0.796,5.968,5.052
Aston Villa,21.087,1566.043,2.130,2.364,1.609,1.628,21.000,15.870,2.696,0.174,1.913,2.165,5.631,3.000
"Aston Villa,Chelsea",26.000,1574.000,3.000,3.700,1.000,4.319,39.000,40.000,0.000,0.000,3.000,3.700,9.897,3.717
Brighton,19.269,1369.692,1.500,2.089,0.923,1.396,18.538,13.731,1.692,0.231,1.269,1.826,5.767,3.464
Burnley,19.400,1465.480,1.280,1.513,0.800,1.102,14.960,10.640,1.880,0.000,1.160,1.422,3.231,1.663
Chelsea,20.920,1496.720,2.240,2.772,1.520,1.874,22.280,17.960,1.960,0.120,1.920,2.467,8.412,5.736
"Chelsea,Fulham",31.000,1988.000,1.000,3.330,0.000,1.245,35.000,17.000,3.000,0.000,1.000,3.330,7.615,3.747
Crystal Palace,21.375,1567.042,1.625,1.479,1.208,1.041,14.542,11.000,2.250,0.083,1.500,1.352,3.787,2.276
Everton,18.179,1307.786,1.607,1.762,1.143,1.204,14.000,10.571,2.071,0.071,1.464,1.653,4.851,2.983
"Everton,Southampton",22.000,1660.000,3.000,2.281,3.000,1.263,29.000,17.000,0.000,0.000,3.000,2.281,5.552,2.234
Fulham,18.444,1319.704,0.926,1.402,0.667,0.944,15.074,11.741,2.370,0.111,0.815,1.233,4.110,2.623
Leeds,22.826,1634.043,2.609,2.602,1.957,1.976,22.696,17.043,2.652,0.043,2.435,2.470,8.238,4.963
Leicester,19.148,1393.630,2.370,2.189,1.667,1.337,17.889,13.259,2.222,0.000,2.000,1.851,6.190,3.960
Liverpool,19.000,1383.704,2.370,2.669,1.593,1.955,22.259,16.815,1.481,0.000,2.148,2.500,8.427,5.272
"Liverpool,Southampton",18.000,941.000,3.000,2.557,0.000,0.763,18.000,4.000,1.000,0.000,3.000,2.557,5.955,2.768
Manchester City,20.042,1521.167,3.208,3.175,2.083,2.224,24.125,18.250,1.833,0.083,3.000,2.890,10.638,7.118
Manchester United,18.630,1354.889,2.519,2.295,1.852,1.608,19.111,15.000,2.333,0.037,2.185,2.013,7.109,4.377
Newcastle United,19.731,1406.269,1.385,1.567,1.000,1.129,14.500,10.692,2.308,0.115,1.154,1.391,4.276,2.392
Sheffield United,18.815,1350.778,0.667,1.227,0.444,0.949,11.630,9.185,2.593,0.111,0.556,1.114,3.754,2.350
Southampton,17.593,1265.111,1.556,1.520,1.111,0.949,13.556,9.481,1.778,0.111,1.370,1.351,3.862,2.477
Tottenham,22.083,1567.458,2.750,2.410,2.083,1.596,18.500,13.125,2.208,0.083,2.542,2.251,6.886,4.224
West Bromwich Albion,17.821,1272.964,1.179,1.245,0.714,0.813,11.607,8.357,1.679,0.143,1.036,1.137,2.729,1.365
"West Bromwich Albion,West Ham",11.000,533.000,0.000,0.206,0.000,0.540,4.000,3.000,2.000,0.000,0.000,0.206,0.831,0.166
West Ham,21.739,1590.391,2.478,2.631,1.913,1.872,19.783,14.435,2.087,0.130,2.391,2.499,6.461,3.336
Wolverhampton Wanderers,18.889,1357.148,1.222,1.427,0.741,0.929,16.667,12.370,1.778,0.037,1.074,1.314,3.480,2.113

**12. Menggunakan Cross Tabulation**
- Cross Tabulation digunakan ketika ingin menganalisis `data kategori dan data kategori`

In [54]:
dfnew.position.unique()

array(['F', 'F M S', 'M S', 'F S', 'M', 'F M', 'D M', 'D S', 'D',
       'D F M S', 'D M S', 'GK', 'S', 'GK S'], dtype=object)

In [55]:
dfnew.team_title.unique()

array(['Tottenham', 'Liverpool', 'Manchester United', 'Leeds', 'Everton',
       'Leicester', 'Aston Villa', 'Manchester City', 'Arsenal',
       'Newcastle United', 'Southampton', 'Burnley', 'Crystal Palace',
       'West Bromwich Albion', 'West Ham', 'Brighton',
       'Arsenal,Newcastle United', 'Chelsea', 'Sheffield United',
       'Wolverhampton Wanderers', 'Fulham', 'Everton,Southampton',
       'Aston Villa,Chelsea', 'Liverpool,Southampton', 'Chelsea,Fulham',
       'West Bromwich Albion,West Ham', 'Arsenal,West Bromwich Albion',
       'Arsenal,Brighton'], dtype=object)

In [65]:
pd.crosstab(dfnew['team_title'], dfnew['position'])

position,D,D F M S,D M,D M S,D S,F,F M,F M S,F S,GK,GK S,M,M S,S
team_title,,,,,,,,,,,,,,
Arsenal,2,1,0,1,7,0,0,5,1,1,0,0,5,3
"Arsenal,Brighton",0,0,0,0,0,0,0,0,0,1,0,0,0,0
"Arsenal,Newcastle United",0,0,0,0,0,0,0,0,0,0,0,0,1,0
"Arsenal,West Bromwich Albion",0,0,0,1,0,0,0,0,0,0,0,0,0,0
Aston Villa,4,0,0,0,2,1,0,4,1,1,0,1,5,4
"Aston Villa,Chelsea",0,0,0,0,0,0,0,0,0,0,0,0,1,0
Brighton,2,1,2,7,0,0,0,6,0,1,0,0,3,4
Burnley,4,0,0,1,3,0,0,2,2,3,0,1,7,2
Chelsea,2,1,1,1,4,0,0,5,2,2,1,0,4,2
"Chelsea,Fulham",0,0,0,0,0,0,0,1,0,0,0,0,0,0
Crystal Palace,4,0,0,2,3,0,0,3,3,2,0,0,6,1
Everton,1,1,1,4,4,0,0,4,1,2,0,1,3,6
"Everton,Southampton",0,0,0,0,0,0,0,1,0,0,0,0,0,0
Fulham,4,2,1,3,4,0,0,3,2,2,0,0,5,1
Leeds,1,0,2,4,2,0,0,2,1,2,0,0,6,3
Leicester,2,0,1,4,4,0,0,2,2,1,0,0,7,4
Liverpool,3,0,0,3,6,0,0,6,1,3,0,0,4,1
"Liverpool,Southampton",0,0,0,0,0,0,0,1,0,0,0,0,0,0
Manchester City,2,0,0,3,4,0,0,7,0,3,0,0,4,1
Manchester United,4,0,0,0,5,0,0,3,1,1,1,1,9,2
Newcastle United,2,0,0,3,7,0,0,4,3,2,0,0,4,1
Sheffield United,2,1,2,2,5,0,0,2,5,1,0,0,4,3
Southampton,5,0,1,1,3,0,0,2,3,2,0,1,5,4
Tottenham,3,0,1,3,3,1,0,4,1,1,0,1,5,1
West Bromwich Albion,1,0,1,1,6,0,0,3,2,2,0,0,9,3
"West Bromwich Albion,West Ham",0,0,0,0,0,0,0,0,0,0,0,0,1,0
West Ham,3,0,2,2,2,0,1,2,2,2,0,2,4,1
Wolverhampton Wanderers,4,1,1,3,3,1,0,3,2,1,1,0,4,3

**13. Menggunakan ANOVA untuk data kategori dan data numerik**

In [50]:
# !pip install scipy

Requirement already satisfied: scipy in c:\users\retha\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: numpy>=1.14.5 in c:\users\retha\anaconda3\lib\site-packages (from scipy) (1.19.2)

In [52]:
import scipy.stats as stats
import statsmodels.api as sm 
from statsmodels.formula.api import ols

In [57]:
model = ols('goals ~ team_title', data = dfnew).fit()


anova_result = sm.stats.anova_lm(model, typ = 2)
print(anova_result)

              sum_sq     df      F  PR(>F)
team_title   277.640   27.0  0.919   0.585
Residual    5530.429  494.0    NaN     NaN